Setting.create(key: "newswire_api_key", setting_type: "nytimes", value: "2c708e7af0c925595b9d3a2132b89070:5:64461877")
Setting.create(key: "login", setting_type: "bitly", value: "dgaff")
Setting.create(key: "api_key", setting_type: "bitly", value: "R_9ceb018f79a8cc844347246db9e123c0")
Setting.create(key: "consumer_key", setting_type: "twitter", value: "j5ZxyEiRBO4zjBmTP0b2Vg")
Setting.create(key: "logo", setting_type: "nytimes", value: "http://politicalfiber.com/wp-content/uploads/2012/02/The_New_York_Times_logo.jpg")
Setting.create(key: "consumer_secret", setting_type: "twitter", value: "BldkjXxrPn0P0UZMDVxqtseWkOAEd7hUDZACuiindlg")
PositionMetric.create(name: "keywords", metric_type: "semantic")
PositionMetric.create(name: "location", metric_type: "geographic")
PositionMetric.create(name: "authors", metric_type: "semantic")
PositionMetric.create(name: "publication", metric_type: "semantic")
PositionMetric.create(name: "sub_publication", metric_type: "semantic")
PositionMetric.create(name: "section", metric_type: "semantic")
PositionMetric.create(name: "related_urls", metric_type: "semantic")
PositionMetric.create(name: "news_type", metric_type: "semantic")
ImportanceMetric.create(name: "bitly_clicks", metric_type: "importance")
ImportanceMetric.create(name: "stumble_upon", metric_type: "importance")
ImportanceMetric.create(name: "reddit", metric_type: "importance")
ImportanceMetric.create(name: "facebook_commentsbox_count", metric_type: "importance")
ImportanceMetric.create(name: "facebook_click_count", metric_type: "importance")
ImportanceMetric.create(name: "facebook_total_count", metric_type: "importance")
ImportanceMetric.create(name: "facebook_comment_count", metric_type: "importance")
ImportanceMetric.create(name: "facebook_like_count", metric_type: "importance")
ImportanceMetric.create(name: "facebook_share_count", metric_type: "importance")
ImportanceMetric.create(name: "delicious", metric_type: "importance")
ImportanceMetric.create(name: "google_plus_one", metric_type: "importance")
ImportanceMetric.create(name: "buzz", metric_type: "importance")
ImportanceMetric.create(name: "twitter", metric_type: "importance")
ImportanceMetric.create(name: "diggs", metric_type: "importance")
ImportanceMetric.create(name: "pinterest", metric_type: "importance")
ImportanceMetric.create(name: "linked_in", metric_type: "importance")
Source.create(title: "The New York Times", location: "New York City")
UserPositionMetric.create(name: "keywords", metric_type: "semantic")
UserPositionMetric.create(name: "location", metric_type: "geographic")
